services:
  monitor:
    build:
      context: ./goModelController
      dockerfile: Dockerfile.go  # Explicitly specify the Dockerfile name
    ports:
      - "8000:8000"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheusPart/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafanaView/provisioning:/etc/grafana/provisioning
      - ./grafanaView/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json